### ISSUE TITLE
p.a.relationfield doesn't clean up relations to removed content for Dexterity CT's

### ISSUE THREAD

**Issue by fredvd** [plone/plone.app.relationfield#10]
Related items using plone.app.relationfield with Dexterity Items are broken at the moment when you delete related contents. 

This manifests itself in for example plone.app.contenttypes implementations, both in Plone 4.3.x with p.a.c 1.1bX  as well as in Plone 5 coredev.  Specifically what is broken is that if you create a related item from contentitem 1 to content item 2 and then remove content item 2, the relation is not cleaned up and iterating over the relations in content item 1 breaks.

We stumbled upon this when creating a custom content type with relations using plone.app.relationfield. The problem doesn't occur with Archetypes based relations. There are event subscriptions in z3c.relationfield for IObjectRemovedEvent and IObjectModifiedEvent to clean up relations and they work for Archetypes CT's (like using the default related items functionality in
Plone 4.3.X)  but not with Dexterity CT's as in p.a.contenttypes.  

The quick fix for my custom CT is to iterate over all relations and to filter those out with r.isBroken() : [r for r in self.context.related_articles if not r.isBroken()] and I use those in views.

---

Feedback From Philip Bauer on the Plone developer Mailinglist:

from a first glimse at the issue it seems plone.app.relationfield should make sure that the objects with relations implement z3c.relationfield.interfaces.IHasOutgoingRelations or the event-handler in z3c.relationfield also handles plone.app.relationfield.interfaces.IDexterityHasRelations. The main problem is that plone.app.relationfield does not have the relevant tests. (#2)

**Comment by gforcada** [comment]
Seems that test meanwhile have been added according to @jensens in #2  🍀 

Feel free to re-open if there are still missing something missing!
