### ISSUE TITLE
Document which versions work with 4.3 and 5.0

### ISSUE THREAD

**Issue by do3cc** [plone/plone.app.relationfield#16]
According to the change notes, with the minor release 1.2.2 plone.app.relationfield added a dependency to something Plone5 related, plone.app.widgets. What is the right version to use this package safely with 4.3.x?

**Comment by jensens** [comment]
following up here, also Travis CI is red. Is this package is still supposed to be used with 4.3.x?

**Comment by do3cc** [comment]
yeah of course

**Comment by do3cc** [comment]
What about the 1.2.x branch?
1.2.1 contained changed for Plone 4.3
1.2.2 added Plone 5 only dependencies

**Comment by jensens** [comment]
the 1.2.x branch is alive
this is version hell. 
the release after the drop of 4.3.x support should have been a 1.3.0 
i think this is difficult to fix now, only by adding a fourth level like 1.2.1.1 and bumping master to 1.3 at least

**Comment by do3cc** [comment]
I propose to create a 1.2.3 release. @cedricmessiant already cleaned up the 1.2.x branch
I did the same with [plone.testing 4.2.1](https://pypi.python.org/pypi/plone.testing/4.2.1#id8)

**Comment by cedricmessiant** [comment]
+1 !
The aim of 1.2.x branch is Plone 4 compatibility

**Comment by jensens** [comment]
I think we need to ping the @plone/release-team in order to make this happen.

**Comment by do3cc** [comment]
Really? why? I don't know the processes any more it seems

**Comment by gforcada** [comment]
@jensens to make *what* happen? A release can be done by ``plone, timo, do3cc, esteele, laurencerowe, alecm, optilude, davisagli``.

**Comment by mauritsvanrees** [comment]
The `CHANGES.rst` no longer has the backwards incompatible changes of 1.2.2, it only lists a plone.rfc822 change. I would say the changelog entries need to be there so the CHANGES.rst is historically accurate. A new section for 1.2.3 should then beadded, with a comment like 'reverted changes from 1.2.2 that introduced a too new plone.app.widgets dependency' or something like that.
We should add `setup.py` classifiers for good measure.
Then I or someone else from the mentioned people can do a release.

**Comment by cedricmessiant** [comment]
It seems to me that HISTORY.txt is ok in the branch, isn't it ? (there is no `CHANGES.rst` in the 1.2.x branch)

https://github.com/plone/plone.app.relationfield/blob/1.2.x/docs/HISTORY.txt

**Comment by mauritsvanrees** [comment]
Ah, sorry, I was looking locally in a checkout in the coredev 4.3 buildout, but that is the 1.x branch, not 1.2.x.

**Comment by mauritsvanrees** [comment]
I did some minor cleanups, like moving the history to a `CHANGES.rst` file. :-)
I have released 1.2.3 and updated coredev 4.3 to use that version and the 1.2.x branch.

I'll close this issue, please reopen if there is anything else that needs clearing up.

**Comment by cedricmessiant** [comment]
Thanks @mauritsvanrees !
