### ISSUE TITLE
make it a named behavior

### ISSUE THREAD

**Issue by iham** [plone/plone.app.relationfield#27]
to move from dotted name behavior registration to named behaviors and gain some flexibility, but no new restrictions.

we would no more need to care about which behavior interface is implemented by using a name.

this is a simple task:
adding name="plone.relateditems" would do the trick.

```xml
    <plone:behavior
        zcml:condition="installed plone.behavior"
        title="Related items"
        name="plone.relateditems"
        description="Adds the ability to assign related items"
        provides=".behavior.IRelatedItems"
        />
```

**Comment by iham** [comment]
did it :)

@gforcada can you release that to pypi in order to have this minor fix available as packaged asap?

**Comment by gforcada** [comment]
I can do that if you create the news entry for this change :wink:

**Comment by iham** [comment]
@gforcada thanks for reminding me :) - done.

**Comment by gforcada** [comment]
Release done: 2.0.1 :tada:
